apiVersion: batch/v1
kind: CronJob
metadata:
  name: the-automatic-manager-calendar-monitor
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
          - name: the-automatic-manager-calendar-monitor
            image: [].dkr.ecr.us-west-2.amazonaws.com/the-automatic-manager:0.0.4
            imagePullPolicy: Always
            command:
            - /opt/the-automatic-manager/monitor_calendar_linux
            env:
            - name: REDIS_URL
              value: redis://redis-master
            - name: GOOGLE_OAUTH2_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: oauth
                  key: GOOGLE_OAUTH2_CLIENT_ID
            - name: GOOGLE_OAUTH2_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: oauth
                  key: GOOGLE_OAUTH2_CLIENT_SECRET
            - name: ATLASSIAN_OAUTH2_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: oauth
                  key: ATLASSIAN_OAUTH2_CLIENT_ID
            - name: ATLASSIAN_OAUTH2_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: oauth
                  key: ATLASSIAN_OAUTH2_CLIENT_SECRET
            - name: ATLASSIAN_JIRA_BASIC_AUTH_USER
              valueFrom:
                secretKeyRef:
                  name: oauth
                  key: ATLASSIAN_JIRA_BASIC_AUTH_USER
            - name: ATLASSIAN_JIRA_BASIC_AUTH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: oauth
                  key: ATLASSIAN_JIRA_BASIC_AUTH_TOKEN
            - name: NOTION_KEY
              valueFrom:
                secretKeyRef:
                  name: oauth
                  key: NOTION_KEY
            volumeMounts:
            - name: config
              mountPath: /opt/the-automatic-manager/.env
              subPath: .env
              readOnly: true
          volumes:
          - name: config
            configMap:
              name: the-automatic-manager-calendar-monitor-config
              items:
              - key: "dot.env"
                path: ".env"
          terminationGracePeriodSeconds: 30
          dnsPolicy: ClusterFirst
          securityContext: {}
          schedulerName: default-scheduler

